# -*- coding: utf-8 -*-
"""Forage-TaskFour.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1htYmmLItaVG9xB-kYzoHpoiy9K2uAq5A
"""

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier


data = pd.read_csv('Task 3 and 4_Loan_Data.csv')

# Defining the number of buckets
num_buckets = 10

# Prepare the data for decision tree model
X = pd.DataFrame(data['fico_score'])
y = pd.DataFrame(data['default'])

# Train the decision tree classifier to create buckets
dt = DecisionTreeClassifier(max_leaf_nodes=num_buckets, random_state=42)
dt.fit(X, y)

# Predicting the bucket labels for each FICO score
data['fico_bucket'] = dt.apply(X)

# Calculating default rate and fico score range for each bucket
bucket_stats = data.groupby('fico_bucket').agg(
    default_rate=('default', 'mean'),
    fico_scores=('fico_score', lambda x: (x.min(), x.max()))
).reset_index()

# Sorting the default rates by FICO bucket
bucket_stats = bucket_stats.sort_values(by='default_rate', ascending=False).reset_index(drop=True)

# Displaying the result
print(bucket_stats)